<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>

  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Hash\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HSEQ.API.Model\HSEQ.API.Model.csproj" />
    <ProjectReference Include="..\HSEQ.Common\HSEQ.Common.csproj" />
  </ItemGroup>

</Project>
